### PR TITLE
update Sechelt for new API libs

### PR DESCRIPTION
**Pull request by cvan**
I'm having some trouble getting Sechelt to render correctly with three r74 + the new VREffect:

screenshot 2016-02-26 00 12 20

Fine on `master`:

screenshot 2016-02-26 00 12 35

In this branch (but not on `master`) this appears In Firefox's Console:

> `Error: WebGL: drawArrays: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)`

I spent quite some time trying to determine where the problem was, but no luck. (I also tried using the VREffect from r74, not Brandon's branch, but also no luck.) Ideas, @caseyyee?

### CODE REVIEW

**Comment by ngokevin** [comment]
Where'd you get the time machine to get r76? :)

**Comment by cvan** [comment]
> Where'd you get the time machine to get r76? :)

fixed

image

**Comment by cvan** [comment]
ping @caseyyee @dmarcos @ngokevin

**Comment by cvan** [comment]
lol this doesnt work

**Comment by caseyyee** [comment]
oops!

**Pull request merged**
